FROM migrate/migrate:latest

# Copy migration files
COPY migrations/ /migrations/

# Set working directory
WORKDIR /migrations

# Default command to run migrations
CMD ["migrate", "-path", "/migrations", "-database", "postgres://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=${DB_SSL_MODE}", "up"]
